name: Test and Code Coverage Report
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: routeinn_api
      DB_USERNAME: admin
      DB_PASSWORD: root
      JWT_SECRET: aOb7cxWqVbAIFOZ24CAjrLrOeeBYcrUmeqtBF0GOUYdFHMQfDudO7EKybyknJjhe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Install dependencies
        run: |
          cp .env.example .env
          composer install
          composer dump-autoload
          php artisan config:cache
          php artisan key:generate
      - name: Generate code coverage report
        run: |
          mkdir coverage
          vendor/bin/phpunit --coverage-html coverage-report
          cp -r ./coverage-report/* ./coverage/
      - name: config git
        run: |
          git config --global user.name "tgp97-ha"
          git config --global user.email "katanan2507@gmail.com"
          git config --global user.password "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"
          git config --global --add safe.directory /github/workspace
      - name: add code coverage folder
        run: |
          git fetch origin
          git add coverage
          git commit -m "Add coverage folder"
          git checkout develop
          git merge main --allow-unrelated-histories
          git config --global --add safe.directory /github/workspace
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: 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
          branch: origin/develop